# Generated by Django 5.2.14 on 2026-05-31 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ForumUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=500, unique=True)),
                ("url", models.URLField(max_length=1000)),
                ("content_type", models.CharField(max_length=50)),
                ("size_bytes", models.PositiveIntegerField()),
                ("used", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("first_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forum_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "forum_upload",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["used", "created_at"],
                        name="forum_uploa_used_842a38_idx",
                    )
                ],
            },
        ),
    ]
