# Generated by Django 5.2.14 on 2026-05-13 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Render',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('prompt', 'Prompt textuel'), ('sketch', 'Croquis 2D'), ('screenshot', 'Capture 3D')], max_length=20)),
                ('output_type', models.CharField(choices=[('2d', 'Image 2D'), ('3d', 'Modèle 3D')], default='2d', max_length=10)),
                ('prompt', models.TextField(blank=True)),
                ('style_hint', models.CharField(blank=True, max_length=200)),
                ('input_image', models.ImageField(blank=True, null=True, upload_to='renders/inputs/%Y/%m/')),
                ('result_image', models.ImageField(blank=True, null=True, upload_to='renders/outputs/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('done', 'Terminé'), ('failed', 'Échoué')], db_index=True, default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('provider', models.CharField(blank=True, max_length=50)),
                ('provider_response_id', models.CharField(blank=True, max_length=200)),
                ('cost_credits', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'renders_render',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='renders_ren_user_id_eaee4a_idx'), models.Index(fields=['user', 'status'], name='renders_ren_user_id_f7b23f_idx')],
            },
        ),
    ]
