# Generated by Django 5.2.14 on 2026-05-17 18:26

import apps.projects.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='projects/thumbnails/%Y/%m/')),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'projects_project',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('format', models.CharField(choices=[('glb', 'GLB'), ('gltf', 'glTF'), ('obj', 'Wavefront OBJ'), ('fbx', 'FBX'), ('stl', 'STL')], max_length=10)),
                ('file', models.FileField(upload_to='projects/models/%Y/%m/')),
                ('mtl_file', models.FileField(blank=True, help_text='Fichier .mtl associé (uniquement pour les .obj)', null=True, upload_to='projects/models/%Y/%m/')),
                ('file_size_bytes', models.BigIntegerField(help_text='Taille totale (file + mtl) — utilisée pour les quotas storage')),
                ('position', models.JSONField(default=apps.projects.models._default_transform)),
                ('rotation', models.JSONField(default=apps.projects.models._default_transform)),
                ('scale', models.JSONField(default=apps.projects.models._default_scale)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imported_models', to='projects.project')),
            ],
            options={
                'db_table': 'projects_imported_model',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('note', 'Note'), ('measure', 'Mesure'), ('marker', 'Marqueur')], default='note', max_length=20)),
                ('position', models.JSONField()),
                ('content', models.TextField(blank=True)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='projects.project')),
            ],
            options={
                'db_table': 'projects_annotation',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('version', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scene', to='projects.project')),
            ],
            options={
                'db_table': 'projects_scene',
            },
        ),
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, default=apps.projects.models._generate_share_token, max_length=64, unique=True)),
                ('permission', models.CharField(choices=[('view', 'Lecture seule')], default='view', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_share_links', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='projects.project')),
            ],
            options={
                'db_table': 'projects_share_link',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['user', '-updated_at'], name='projects_pr_user_id_5d1716_idx'),
        ),
    ]
