# Generated by Django 5.2.14 on 2026-06-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminauditlog',
            name='action',
            field=models.CharField(choices=[('user.ban', 'Bannir un user'), ('user.unban', 'Réactiver un user'), ('user.promote_staff', 'Promouvoir staff'), ('user.demote_staff', 'Retirer staff'), ('user.ban_forum', 'Bannir du forum'), ('user.unban_forum', 'Débannir du forum'), ('user.pseudo_change', 'Changer le pseudo'), ('topic.pin', 'Épingler un topic'), ('topic.unpin', 'Désépingler un topic'), ('topic.lock', 'Verrouiller un topic'), ('topic.unlock', 'Déverrouiller un topic'), ('topic.delete', 'Supprimer un topic'), ('reply.delete', 'Supprimer une réponse'), ('reply.mark_solution', 'Marquer solution')], max_length=50),
        ),
    ]
